# Generated by Django 4.2.17 on 2024-12-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_employee_position_alter_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(verbose_name='Зарплата'),
        ),
    ]
