# Generated by Django 4.2.17 on 2024-12-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_order',
            options={'ordering': ('date',), 'verbose_name': 'заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='client_order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('gathered', 'Собран'), ('delivered', 'Доставлен'), ('issued', 'Выдан')], default='accepted', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
