# Generated by Django 4.2.17 on 2024-12-09 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_client_order_options_alter_client_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
            ],
            options={
                'db_table': 'product_with_reviews',
                'managed': False,
            },
        ),
    ]
